[theme]
# Primary accent color for interactive elements
primaryColor = "#000000"

# Background color for main content area
backgroundColor = "#FFFFFF"

# Background color for sidebar and interactive widgets
secondaryBackgroundColor = "#FFFFFF"

# Color used for almost all text
textColor = "#000000"

# Font family for all text in the app, except code blocks
font = "sans serif"

[server]
fileWatcherType = "none"
runOnSave = false
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[logger]
level = "error" 